development:
  solr:
    hostname: localhost
    port: 8980
    log_level: DEBUG
  auto_commit_after_request: true
  
test:
  solr:
    hostname: localhost
    port: 8981
    log_level: OFF

production:
  solr:
    hostname: localhost
    port: 8982
    log_level: WARNING
  auto_commit_after_request: true    